### PR TITLE
Image meta manager 8 json storage

### PR DESCRIPTION
**Pull request by joshua-lehmann**

### CODE REVIEW

**Comment by joshua-lehmann** [comment]
@theGreyPilgrim42 
Also removed the module-info.java file since it makes using any dependencies more complicated and it is not required, only if you have a modular java fx project, which we do not have. But make sure to download and use a JDK which has Java FX included and built in like this one: https://www.azul.com/downloads/?version=java-17-lts&os=windows&architecture=x86-64-bit&package=jdk-fx

**Comment by theGreyPilgrim42** [comment]
I needed to add the parent folder to the fxml-argument of the loadFXML-method in the App.java file in order to be able to open the JavaFX application. Does it work like this for you too @joshua-lehmann ? 
Otherwise it looks fine for a draft. Maybe we should automatically set the album id when we create it.

**Comment by joshua-lehmann** [comment]
> I needed to add the parent folder to the fxml-argument of the loadFXML-method in the App.java file in order to be able to open the JavaFX application. Does it work like this for you too @joshua-lehmann ? Otherwise it looks fine for a draft. Maybe we should automatically set the album id when we create it.

Thanks for fixing the path of the fxml file! I actually changed the project structure and added the views folder without yet testing the application again, and indeed we need to specify the right folder. Thanks for fixing it, works for me as well.
Regarding the album ID, I agree it should be set in the constructor, I will do that.

**Review by theGreyPilgrim42 — APPROVED** [review]
I checked the changes, the tests pass and the Scene can still be loaded.

**Pull request merged**
