### PR TITLE
Scenes

### PR DESCRIPTION
**Pull request by theGreyPilgrim42**
Add basic gui with the following views:
- Library
- Album
- Upload
Also added methods to the PrimaryController to test dynamically adding nodes.

### CODE REVIEW

**Comment by joshua-lehmann** [comment]
Be careful, do not merge into main, but into master. You can edit your PR to change that.

**Comment by theGreyPilgrim42** [comment]
Thanks for the heads up.

**Review by joshua-lehmann — APPROVED** [review]
Looks good to me, check if everything still works locally after my rebase. If everything works you can merge.

**Comment by theGreyPilgrim42** [comment]
Everything works for me, so I'll merge it.

**Pull request merged**
